#!/usr/bin/expect -f
set timeout 2

set LOG [lrange $argv 0 0]
set VIP [lrange $argv 1 1]
set PASS [lrange $argv 2 2]

spawn ./ip_vipnet.sh
sleep 10 
expect "$LOG@$VIP's password:"
send -- "$PASS"
sleep 5
send -- "machine halt\r"
expect eof
